### ISSUE TITLE
Migrate DNS records to switch viveelsuenocr.org to new website

### ISSUE THREAD

**Issue by Auspicus** [Auspicus/viveelsueno#35]
I have all the information for this. I will need the goahead from Rebecca before I start moving the site over.

**Comment by edisch** [comment]
Let me know if you're ready to move the site over. I've done all the last minute tweaks.

**Comment by edisch** [comment]
@Viveelsueno Let me know if you're ready to move the site over. I've done all the last minute tweaks.

**Comment by edisch** [comment]
@Viveelsueno This is the final step to the get the site up on viveelsuenocr.org.
