### ISSUE TITLE
Add logos to the participant teasers

### ISSUE THREAD

**Issue by Auspicus** [Auspicus/viveelsueno#39]
Default logo will be the VES seal
![ves-graduate-seal](https://user-images.githubusercontent.com/35813084/38281499-4dac0da8-3757-11e8-96e4-de5e3bf6c321.jpg)

If the participant has their own logo, that will be used.

![image](https://user-images.githubusercontent.com/1893118/39663780-53ab406c-502e-11e8-9827-efe3c4a40f62.png)

**Comment by Viveelsueno** [comment]
Ok but almost all have logos.

**Comment by edisch** [comment]
@Viveelsueno Can you please upload Iris's logo again here? It didn't upload properly on the other ticket.

**Comment by Viveelsueno** [comment]
![26196335_1607836249296596_6275377540726537741_n](https://user-images.githubusercontent.com/35813084/39898373-a22dcb76-5473-11e8-86f2-b91b82d089ae.jpg)

**Comment by edisch** [comment]
> I think I have all the logos more or less. I just need to extract them from some of the old pages. If you have the originals of all of them stored somewhere that would be a huge help. Maybe we could see if Zac still has copies of the originals?

Copying this into here for reference.

**Comment by Viveelsueno** [comment]
I think I have all of them..do you need the ones from the past years?  I
can send them to you

**Comment by edisch** [comment]
Yeah, if you could add them all in here that would be great. If you could name the files the names of the participant they are for as well so I can easily identify who to add them to in forestry.

**Comment by edisch** [comment]
Or you could just add them directly into forestry. It might be faster for you to do that? Do you know how to do that?

**Comment by edisch** [comment]
Let's leave this one open until we finish importing all the new participants for 2018.

**Comment by edisch** [comment]
> Also Rocio Navarette's business is called Rossi's Dream

> Can we remove where it says unavailable under the people that don't have contact numbers please?
