### ISSUE TITLE
2016 and 2017 logos

### ISSUE THREAD

**Issue by Viveelsueno** [Auspicus/viveelsueno#41]

**Comment by edisch** [comment]
@Viveelsueno The best way to do this might be to just zip them up into a folder and name each logo with the participants name. Does that make sense? You can upload zip files here in GitHub.

**Comment by Viveelsueno** [comment]
Sheyla Rosales DInarte-no logo

**Comment by Viveelsueno** [comment]
Elisabeth Bran Rosales-no logo

**Comment by Viveelsueno** [comment]
Anadilsa Rosales Diaz
Las Palmeras-no logo

**Comment by Viveelsueno** [comment]
Moises Lopez
Tico Tech-no logo

**Comment by Viveelsueno** [comment]
Hannia & Nathalie Matarrita
Aguamarina Delivery Food
![img-20161109-wa0002](https://user-images.githubusercontent.com/35813084/40317853-fa09099a-5cdf-11e8-93c5-be756be1c91a.jpg)

**Comment by Viveelsueno** [comment]
Dayana Reyes Garcia
Repostería Los Reyes
no logo

**Comment by Viveelsueno** [comment]
Karina Rosales Marchena
Lotus Massage
no logo
